### PR TITLE
Automatic Doorbell

### PR DESCRIPTION
**Pull request by DragonUncaged**
Door Bell
Related Issue

Closes: #231 

Describe the changes you've made
Built API (Driver That can be used with any functionality for LCD) tested it be printing names and numbers on LCD.

- [x] GSSOC22 Participant
- [x] Contributor

Describe the changes you've made

I have added code, readme, images and simulation video to implement

Type of change
What sort of change have you made:
## Type of change
What sort of change have you made:

* [x]  Bug fix (non-breaking change which fixes an issue)
* [ ]  New feature (non-breaking change which adds functionality)
* [x]  Code style update (formatting, local variables)
* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  This change requires a documentation update

## How Has This Been Tested?
I have run the code before and after adding my code and observe the changes which is making it bug free.

## Checklist:
* [x]  My code follows the guidelines of this project.
* [x]  I have performed a self-review of my own code.
* [x]  I have commented my code, particularly wherever it was hard to understand.
* [x]  I have made corresponding changes to the documentation.
* [x]  My changes generate no new warnings.
* [x]  I have added tests that prove my fix is effective or that my feature works.
* [x]  Any dependent changes have been merged and published in downstream modules.

image

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add appropriate comments to the code to get good understanding of the project. Be elaborate with README file.
Also this project should go into "Minor Scripts/Arduino" repository @DragonUncaged

**Comment by DragonUncaged** [comment]
> Add appropriate comments to the code to get good understanding of the project. Be elaborate with README file. Also this project should go into "Minor Scripts/Arduino" repository. Issue title and PR title should be same. @DragonUncaged

Done!!

**Comment by DragonUncaged** [comment]
> Add appropriate comments to the code to get good understanding of the project. Be elaborate with README file. Also this project should go into "Minor Scripts/Arduino" repository. Issue title and PR title should be same. @DragonUncaged

done !!

**Review by prathimacode-hub — APPROVED** [review]
PR approved. ✨@DragonUncaged

**Pull request merged**
