### PR TITLE
temperature sensing with arduino task done

### PR DESCRIPTION
**Pull request by ritikalohia**
added README file, along with schematic diagram, simulation video and code.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly add PR template, add up the details and issue number. Issue title and PR title should be same. For README.md file, we have a template as well to follow

[PR Template](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/pullrequest_template.md)
[README.md](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/readme_template.md)  

Rename your project folder name as "Temperature Sensing" @ritikalohia

**Comment by ritikalohia** [comment]
ok, I will do it asap.

**Comment by prathimacode-hub** [comment]
Pull request template should be here in commit message and README.md template is different that has all details regarding the project. And few more changes aren't done yet. Kindly check it up. @ritikalohia

**Review by geetaroraqaz — COMMENTED** [review]
change temperature to temperature sensor

**Comment by ritikalohia** [comment]
## Related Issue 

- Info about the related issue 

- [ ] DWOC Participant  
- [x] SWOC Participant 
- [ ] Contributor

Closes: #14 that will be closed through this PR

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
It has been tested on the Tinkercad, and simulation video is provided and it works properly.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Uploaded in the images folder.
 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great start. Welcome to repo. Keep going. 🎉👏@ritikalohia

**Pull request merged**
