### PR TITLE
overflow managed and cards section improved

### LINKED ISSUE #152: Improvement in UI of specific sections
- Adding glass morphism and background will make the cards more interactive.
- The social icons are shown twice both in let's connect form and in the footer. A footer that contains the social information as well as the let's connect form will enhance the UI. 
- The website has a scrollbar at the bottom which is adding extra width of the website and is of no use.

The image below shows the issue of extra width.

Screenshot (410)

### PR DESCRIPTION
**Pull request by Nitya-S27**
# Description

Managed the overflow and changed the UI of cards.
and will work on the footer next.

Fixes #152 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

The updated card UI is responsive at various viewports.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Use the PR template provided. Include details you had done into the template along with the issue number. @Nitya-S27

**Review by Dhruvsinghjadon — COMMENTED** [review]
Approved by me

**Comment by prathimacode-hub** [comment]
Could you include the PR template along with details of the PR and issue number using issue template provided. @Nitya-S27

**Comment by Nitya-S27** [comment]
> Could you include the PR template along with details of the PR and issue number using issue template provided. @Nitya-S27

yes I have updated the PR.

**Comment by prathimacode-hub** [comment]
Include the issue number in your PR and not PR number. @Nitya-S27

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good observation. Keep going. 🙌👏@Nitya-S27

**Comment by Nitya-S27** [comment]
> PR approved. Good observation. Keep going. 🙌👏@Nitya-S27

Thankyou :)

**Pull request merged**
