### PR TITLE
Water level controller

### PR DESCRIPTION
**Pull request by baibhav3211**
## Related Issue 

- Info about the related issue 

- [ ] DWOC Participant  
- [x] SWOC Participant 
- [ ] Contributor

Closes: #30 

### Describe the changes you've made

Added a project to demonstrate water level contoller using arduino and buzzer.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The project is verified on tinkercad platform and the video of the simulation is also added.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

Uploaded in the images folder.

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project should go into "/Minor Scripts/Arduino" repo
Rename images folder as "Images"

@baibhav3211

**Comment by baibhav3211** [comment]
Now check @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great going. Keep progressing. 👍👌@baibhav3211

**Review by geetaroraqaz — COMMENTED** [review]
Rectify tinkercad, jumpercables, simulation  spellings.

**Pull request merged**
