### PR TITLE
Remote Control Home

### PR DESCRIPTION
**Pull request by DragonUncaged**
#254 

Related Issue
Info about the related issue
GSSOC22 Participant
Contributor

Closes: #254 

- [x] GSSOC22 Participant
- [x] Contributor

Describe the changes you've made

I have added code, readme, images and simulation video to implement

Type of change
What sort of change have you made:
## Type of change
What sort of change have you made:

* [x]  Bug fix (non-breaking change which fixes an issue)
* [ ]  New feature (non-breaking change which adds functionality)
* [x]  Code style update (formatting, local variables)
* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  This change requires a documentation update

## How Has This Been Tested?
I have run the code before and after adding my code and observe the changes which is making it bug free.

## Checklist:
* [x]  My code follows the guidelines of this project.
* [x]  I have performed a self-review of my own code.
* [x]  I have commented my code, particularly wherever it was hard to understand.
* [x]  I have made corresponding changes to the documentation.
* [x]  My changes generate no new warnings.
* [x]  I have added tests that prove my fix is effective or that my feature works.
* [x]  Any dependent changes have been merged and published in downstream modules.

preview

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Don't create PR, before getting it assigned. This is against code of conduct. @DragonUncaged

**Comment by DragonUncaged** [comment]
> Don't create PR, before getting it assigned. This is against code of conduct. @DragonUncaged
Oh...
Okay !!

**Comment by DragonUncaged** [comment]
image

image

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👏@DragonUncaged

**Pull request merged**
