### PR TITLE
IoT-Spot : Traffic Lights Controller using Arduino #26 

### PR DESCRIPTION
**Pull request by ritikalohia**
project traffic light controller done.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly add PR template along with details and change your PR title to the issue title. @ritikalohia

**Comment by ritikalohia** [comment]
## Related Issue 

- Info about the related issue 

- [ ] DWOC Participant  
- [x] SWOC Participant 
- [ ] Contributor

Closes: #26  number that will be closed through this PR

### Describe the changes you've made
I have made a new folder named traffic light controller, In which images, video , code and readme file are present.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been simulated on Tinkedcad, video is also in Images folder.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Images and video are uploaded in Images.
 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

**Comment by prathimacode-hub** [comment]
This project should be added in "/Minor Scripts/Arduino/" folder as mentioned over an issue. @ritikalohia

**Comment by ritikalohia** [comment]
## Related Issue 

- Info about the related issue 

- [ ] DWOC Participant  
- [x] SWOC Participant 
- [ ] Contributor

Closes: #26  number that will be closed through this PR

### Describe the changes you've made
I have made a new folder named traffic light controller, In which images, video , code and readme file are present.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been simulated on Tinkedcad, video is also in Images folder.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Images and video are uploaded in Images.
 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

**Review by prathimacode-hub — APPROVED** [review]
Great start. Congrats. Welcome to repo. Keep contributing. 🎉👌@ritikalohia

**Pull request merged**
