### PR TITLE
Burglar Alarm (👍) (check)

### PR DESCRIPTION
**Pull request by DragonUncaged**
#232 

Related Issue
Info about the related issue
To Ring the Bell As Soon As Somebody's Movement Is Observed
Implemented the Arduino for that.

- [x] GSSOC22 Participant
- [x] Contributor

Closes: #232 

Describe the changes you've made

I have added code, readme, images and simulation video to implement

Type of change
What sort of change have you made:
## Type of change
What sort of change have you made:

* [x]  Bug fix (non-breaking change which fixes an issue)
* [ ]  New feature (non-breaking change which adds functionality)
* [x]  Code style update (formatting, local variables)
* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  This change requires a documentation update

## How Has This Been Tested?
I have run the code before and after adding my code and observe the changes which is making it bug free.

## Checklist:
* [x]  My code follows the guidelines of this project.
* [x]  I have performed a self-review of my own code.
* [x]  I have commented my code, particularly wherever it was hard to understand.
* [x]  I have made corresponding changes to the documentation.
* [x]  My changes generate no new warnings.
* [x]  I have added tests that prove my fix is effective or that my feature works.
* [x]  Any dependent changes have been merged and published in downstream modules.

image

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add a PR template, along with your issue number and your PR details to know you as GSSoC contributor for all of your PR's. You can edit the comment using edit option. @DragonUncaged

**Review by prathimacode-hub — APPROVED** [review]
Changes to be done yet. @DragonUncaged

**Comment by prathimacode-hub** [comment]
Oops, you had added in wrong folder. All use case applications should be in "Minor Scripts/Arduino" folder. @DragonUncaged

**Comment by DragonUncaged** [comment]
> Add appropriate comments to the code to get good understanding of the project. Be elaborate with README file. Also this project should go into "Minor Scripts/Arduino" repository. Issue title and PR title should be same. @DragonUncaged

I have elaborated enough and also added enough comments in the code

**Review by prathimacode-hub — APPROVED** [review]
PR approved. ✔@DragonUncaged

**Pull request merged**
