### PR TITLE
IoT-Spot : Visitor counter using Arduino #129

### PR DESCRIPTION
**Pull request by vaishnavighiradkar**
## Related Issue 

- Info about the related issue 

- [X] GSSOC Participant  
- [X] Contributor

Closes: #129 

### Describe the changes you've made

Added a system that will keep track of number of visitors And will display the total number on LCD screen. It also buzzes alarm if someone visits. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

When simulation was started and we bring pointer of ultrasonic distance sensor near to it, it was counted as a visit and piezo buzzed. Also total number of visitors was displayed on the LCD screen. 

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram 
circuit diagram
|

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Rename your project title as "Visitor Counter" 
Include the images in your PR template @vaishnavighiradkar

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub  Ma'am I added the screenshot but I am unable to change mentioned file's name.  I tried it many times.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
What's the file name you want to change? @vaishnavighiradkar

**Comment by vaishnavighiradkar** [comment]
> What's the file name you want to change? @vaishnavighiradkar

I was asked to change the name "Visitor counter" to "Visitor Counter"

**Comment by prathimacode-hub** [comment]
> > What's the file name you want to change? @vaishnavighiradkar
> 
> I was asked to change the name "Visitor counter" to "Visitor Counter"

Ok, let it be. @vaishnavighiradkar

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Interesting project. Great going. ✔👌@vaishnavighiradkar

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub  Ma'am can you add "Approved" label to this merged pull request?

**Pull request merged**
