### PR TITLE
Fixed X scroll (issue #273)

### PR DESCRIPTION
**Pull request by ShivanshAr97**
Fixed X scroll (There was some mistake in commiting the code previous time)

### CODE REVIEW

**Comment by mdnazisharman2803** [comment]
@ShivanshAr97  add the screenshot before the changes made, and after the changes made.. Add issue number

**Comment by ShivanshAr97** [comment]
It is same as 

> @ShivanshAr97 add the screenshot before the changes made, and after the changes made.. Add issue number

PR was #274 which was merged with wrong commit.
This is the PR with correct commit.

Expected output:
image


Currently:
image

**Comment by mdnazisharman2803** [comment]
@prathimacode-hub  since the old pr was merged with wrong commit, so please approve this change but do not add any labels  to avoid any kind of extra pr or points

**Review by mdnazisharman2803 — APPROVED** [review]

**Review by mdnazisharman2803 — DISMISSED** [review]
@prathimacode-hub since the old pr was merged with wrong commit, so please approve this change but do not add any labels to avoid any kind of extra pr or points

**Comment by Harshil-Jani** [comment]
> @prathimacode-hub since the old pr was merged with wrong commit, so please approve this change but do not add any labels to avoid any kind of extra pr or points

Hi ! I have already reverted the Old PR in order to Undo last commits. So, Just merge the revert PR #277 first as it requires the review and then we can merge this #276 . Also, It is really hard to go through each PR changes for the Web Part. We can talk on this and add some preview in the PR itself about how the new changes would look like. Something similar to `netlify-preview` feature in PRs.

**Review by prathimacode-hub — APPROVED** [review]
PR Approved.

**Pull request merged**
