### PR TITLE
Humidity Sensing using arduino

### PR DESCRIPTION
**Pull request by SarthakSKumar**
### Related Issue:
IoT-Spot: Humidity Sensing using Arduino #15

- [x] GSSOC Participant
- [x] Contributor

Closes: #15

### Type of Change:
Added a new folder under Arduino Scripts, which contains files for the "Humidity Sensing using Arduino" Project.
-New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
I have written and tested the code (.ino file) for Arduino. Compiles Successfully.
Attached the block diagram for the Schematic Representation

### Checklist:
- [x] My code follows the guidelines of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SarthakSKumar** [comment]
I haven't added simulation here too. I am not aware of which tool/software I can use for simulations. Wasn't able to find the DHT11 module in TinkerCad

**Comment by prathimacode-hub** [comment]
> I haven't added simulation here too. I am not aware of which tool/software I can use for simulations. Wasn't able to find the DHT11 module in TinkerCad

Module is available as far as I know. Are you checking up through All section or categories? @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> > I haven't added simulation here too. I am not aware of which tool/software I can use for simulations. Wasn't able to find the DHT11 module in TinkerCad
> 
> Module is available as far as I know. Are you checking up through All section or categories? @SarthakSKumar

I checked through the different sections ma'am🙏Not able to find it

**Comment by prathimacode-hub** [comment]
> > > I haven't added simulation here too. I am not aware of which tool/software I can use for simulations. Wasn't able to find the DHT11 module in TinkerCad
> > 
> > 
> > Module is available as far as I know. Are you checking up through All section or categories? @SarthakSKumar
> 
> I checked through the different sections ma'am🙏Not able to find it

Ok, in that case go to the proteus. In my last project, I had used so was sure about finding the component from Tinkercad. @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> > > > I haven't added simulation here too. I am not aware of which tool/software I can use for simulations. Wasn't able to find the DHT11 module in TinkerCad
> > > 
> > > 
> > > Module is available as far as I know. Are you checking up through All section or categories? @SarthakSKumar
> > 
> > 
> > I checked through the different sections ma'am🙏Not able to find it
> 
> Ok, in that case go to the proteus. In my last project, I had used so was sure about finding the component from Tinkercad. @SarthakSKumar

Will check it out ma'am 🙏

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Add simulation file link in README too.
The project file you had added in double folders. .ino file should be in "Arduino/Humidity Sensing using Arduino". This correction and it's good to be merged.

@SarthakSKumar

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great going. 👌🙌@SarthakSKumar

**Comment by prathimacode-hub** [comment]
Your PR has merge conflicts. It might be arised if you haven't made your forked repo even with main repo before creating the PR. Once conflict is resolved, its good to merge. @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> Your PR has merge conflicts. It might be arised if you haven't made your forked repo even with main repo before creating the PR. Once conflict is resolved, its good to merge. @SarthakSKumar

I have sorted out the conflicts ma'am. Please do review

**Pull request merged**
