### PR TITLE
Ping Pong Game using Arduino

### PR DESCRIPTION
**Pull request by SarthakSKumar**
### Related Issue:
IoT-Spot: Ping Pong Game using Arduino #167

- [x] GSSOC Participant
- [x] Contributor

Closes: #167 

### Type of Change:
Added a new folder under Arduino Scripts, which contains files for the "Ping Pong Game using Arduino" Project.
-New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
I have written and tested the code (.ino file) for Arduino. Compiles Successfully.
Attached is the block diagram for the Schematic Representation
Added the simulation video for the project

### Checklist:
- [x] My code follows the guidelines of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Could you drop this project into "/Minor Scripts/Arduino" folder @SarthakSKumar

**Comment by SarthakSKumar** [comment]
I have made the requested changes ma'am. Please review. Thanks @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Highly appreciated and impressive PR. Well done. 👌✔@SarthakSKumar

**Comment by SarthakSKumar** [comment]
> PR approved. Highly appreciated and impressive PR. Well done. 👌✔@SarthakSKumar

Thank you very much ma'am.

**Pull request merged**
