### PR TITLE
Storing Sensory Data to SD Card

### PR DESCRIPTION
**Pull request by SarthakSKumar**
### Related Issue:
IoT-Spot: Storing Sensory Data to SD Card #20

- [x] GSSOC Participant
- [x] Contributor

Closes: #20 

### Type of Change:
Added a new folder under Arduino Scripts, which contains files for the "Storing Sensory Data to SD Card" Project.
-New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
I have written and tested the code (.ino file) for Arduino. Compiles Successfully.
Attached is the block diagram for the Schematic Representation
Added the simulation video for the project

### Checklist:
- [x] My code follows the guidelines of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Dhruvsinghjadon — COMMENTED** [review]
Approved by me, Let others check it

**Comment by SarthakSKumar** [comment]
> Approved by me, Let others check it

Thank you!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only thing it needs, add requirements.txt file with things needed to make this project successful. @SarthakSKumar

**Comment by SarthakSKumar** [comment]
I have made the requested changes ma'am. Please review @prathimacode-hub . Thanks

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good going. Well presented. 🙌👌@SarthakSKumar

**Comment by SarthakSKumar** [comment]
> PR approved. Good going. Well presented. 🙌👌@SarthakSKumar

Thanks ma'am🙏🙏

**Review by Dhruvsinghjadon — COMMENTED** [review]
Good

**Pull request merged**
