### PR TITLE
Safe locker circuit

### PR DESCRIPTION
**Pull request by rk18venom**
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #103 

### Describe the changes you've made

Adding the new project on how to make Safe Lock Circuit Simulation on Tinkercad.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

On Tinker Cad

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | [Screenshort](https://github.com/rk18venom/IoT-Spot/blob/Safe-Lock-Circuit/Minor%20Scripts/Arduino/Safe%20Locker%20Circuit/Images/Circuit%20Image.png) |
 Original Block Diagram | [Block Diagram](https://github.com/rk18venom/IoT-Spot/blob/Safe-Lock-Circuit/Minor%20Scripts/Arduino/Safe%20Locker%20Circuit/Images/Block%20Diagram.pdf) |
 
@prathimacode-hub Mam, Hoping that you will like it.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done : 

Add appropriate comments in code file to get good understanding of the project
Rename your project folder as " Safe Locker Circuit"
Your block diagram and circuit diagram isn't legibly visible.

Kindly do these changes. @rk18venom

**Comment by rk18venom** [comment]
@prathimacode-hub mam, changes have been made as you had suggested to me please review it again.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Block Diagram is too light not visible.
Add README.md file using the template provided along with appropriate details and following links.
Add requirements.txt file with all the things and components needed for this project
Also, add this project in "Minor Scripts/Arduino" folder.

Kindly do these changes. @rk18venom

**Comment by rk18venom** [comment]
@prathimacode-hub can i add pdf file of block diagram

**Comment by rk18venom** [comment]
@prathimacode-hub mam changes made please review it again.

**Review by prathimacode-hub — APPROVED** [review]
Great job. Well done. Keep rocking. PR approved. 👏👌@rk18venom

**Pull request merged**
