### PR TITLE
Display time on LCD using Arduino

### PR DESCRIPTION
**Pull request by SarthakSKumar**
### Related Issue:
IoT-Spot: Display Time on LCD using Arduino #24 

- [x] GSSOC Participant
- [x] Contributor

Closes: #24 

### Type of Change:
Added a new folder under Arduino Scripts, which contains files for the "Display Time on LCD using Arduino" Project.
-New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
I have written and tested the code (.ino file) for Arduino. Compiles Successfully.
Attached the block diagram for the Schematic Representation

### Checklist:
- [x] My code follows the guidelines of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Good work done for the project. Only addon is Just add the PR template to the PR message and include all the given details along with issue number using edit option. It's then ready to be merged. @SarthakSKumar

**Comment by abhisheks008** [comment]
Looks good to me! Do the required changes and the PR is ready to merge @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> Good work done for the project. Only addon is Just add the PR template to the PR message and include all the given details along with issue number using edit option. It's then ready to be merged. @SarthakSKumar

Thank you for your reply. Shall do the needed changes and revert

**Comment by SarthakSKumar** [comment]
> Looks good to me! Do the required changes and the PR is ready to merge @SarthakSKumar

Thank you for your reply 🙏

**Comment by SarthakSKumar** [comment]
> ### Related Issue:
> IoT-Spot: Display Time on LCD using Arduino #24
> 
> * [ ]  GSSOC Partcipant
> * [ ]  Contributor
> 
> Closes: Issue Number #24
> 
> ### Type of Change:
> Added a new folder under Arduino Scripts, which contains files for the "Display Time on LCD using Arduino" Project. -New feature (non-breaking change which adds functionality)
> 
> ### How Has This Been Tested?
> I have written and tested the code (.ino file) for Arduino. Compiles Successfully. Attached the block diagram for the Schematic Representation
> 
> ### Checklist:
> * [ ]  My code follows the guidelines of this project.
> * [ ]  My code follows the guidelines of this project.
> * [ ]  I have performed a self-review of my own code.
> * [ ]  I have commented on my code, particularly wherever it was hard to understand.
> * [ ]  I have made corresponding changes to the documentation.
> * [ ]  My changes generate no new warnings.
> * [ ]  I have added tests that prove my fix is effective or that my feature works.
> * [ ]  Any dependent changes have been merged and published in downstream modules.

I have tried to add according to the PR Template. Please let me know if any other changes are required in the same. I am a newbie to Open Source Contribution. I request your pardon if there are any mistakes in the above 🙏

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Sorry, but just noticed about missing of simulation file. Do add it up in Images and it's good to go. No worries about mistakes, that's how you learn right. @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> Sorry, but just noticed about missing of simulation file. Do add it up in Images and it's good to go. No worries about mistakes, that's how you learn right. @SarthakSKumar

Ma'am, I tried out with TinkerCad for simulations, but I am not able to find the module I have used in the project (RTC Module) to simulate the circuit. I need help here. Waiting for your reply.

**Comment by SarthakSKumar** [comment]
> > Sorry, but just noticed about missing of simulation file. Do add it up in Images and it's good to go. No worries about mistakes, that's how you learn right. @SarthakSKumar
> 
> Ma'am, I tried out with TinkerCad for simulations, but I am not able to find the module I have used in the project (RTC Module) to simulate the circuit. I need help here. Waiting for your reply.

@abhisheks008 Can I expect some help from your end here please?

**Comment by prathimacode-hub** [comment]
@SarthakSKumar, did you find the module? What is the component you're looking for?

**Comment by SarthakSKumar** [comment]
> @SarthakSKumar, did you find the module? What is the component you're looking for?

Not yet ma'am. Could you tell me about another software I could use for simulation? Which contains the RTC DS3231 module.

**Comment by prathimacode-hub** [comment]
You can find this module in proteus 8 @SarthakSKumar

**Comment by prathimacode-hub** [comment]
Is simulation file ready? @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> Is simulation file ready? @SarthakSKumar

Yes ma'am. I had requested for a review as well

**Comment by SarthakSKumar** [comment]
@prathimacode-hub ma'am, can you please review this PR and let me know if any other changes are needed please?

**Review by Dhruvsinghjadon — COMMENTED** [review]
Approved by me

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great spirit. Keep it up. 🎉✨@SarthakSKumar

**Pull request merged**
