### PR TITLE
Site converted in PWA 

### PR DESCRIPTION
**Pull request by ShivanshAr97**
Solves issue #303 

I have converted the site in PWA. Now user can download it in their own device and site can function offline as well

**Screenshots**
image

After installing
image

### CODE REVIEW

**Comment by mdnazisharman2803** [comment]
@ShivanshAr97 this branch too have merge conflict,, you should reolve it

**Comment by ShivanshAr97** [comment]
> @ShivanshAr97 this branch too have merge conflict,, you should reolve it

Done

**Comment by mdnazisharman2803** [comment]
> > @ShivanshAr97 this branch too have merge conflict,, you should reolve it
> 
> Done

i will be looking this soon by tomorrow

**Comment by ShivanshAr97** [comment]
> > > @ShivanshAr97 this branch too have merge conflict,, you should reolve it
> > 
> > 
> > Done
> 
> i will be looking this soon by tomorrow

Alright

**Comment by ShivanshAr97** [comment]
> > > @ShivanshAr97 this branch too have merge conflict,, you should reolve it
> > 
> > 
> > Done
> 
> i will be looking this soon by tomorrow

Did you go through it?

**Comment by mdnazisharman2803** [comment]
> > > > @ShivanshAr97 this branch too have merge conflict,, you should reolve it
> > > 
> > > 
> > > Done
> > 
> > 
> > i will be looking this soon by tomorrow
> 
> Did you go through it?

On it

**Review by mdnazisharman2803 — APPROVED** [review]

**Comment by prathimacode-hub** [comment]
Can you add PR template to this PR? @ShivanshAr97

**Comment by ShivanshAr97** [comment]
> Can you add PR template to this PR? @ShivanshAr97

What changes do I have to make?

**Comment by prathimacode-hub** [comment]
Just add PR template above in commit message. @ShivanshAr97

**Comment by ShivanshAr97** [comment]
> Just add PR template above in commit message. @ShivanshAr97

Done

**Pull request merged**
