### PR TITLE
Keypad Calculator #184

### PR DESCRIPTION
**Pull request by vaishnavighiradkar**
## Related Issue 

- Info about the related issue 

- [X] GSSOC Participant  
- [X] Contributor

Closes: #184 

### Describe the changes you've made

Created a calculator using arduino and other components

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

After simulating, and giving input, correct results were printed on LCD screen.

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |
circuit diagram

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Rename the project name as Keypad Calculator" 
You can also include a detailed description for workflow and setup. @vaishnavighiradkar

**Comment by vaishnavighiradkar** [comment]
Changes done. Please review @prathimacode-hub .

**Comment by vaishnavighiradkar** [comment]
> Changes to be done :
> 
> Rename the project name as Keypad Calculator" You can also include a detailed description for workflow and setup. @vaishnavighiradkar

@prathimacode-hub Ma'am should I change the PR and issue name too?

**Comment by vaishnavighiradkar** [comment]
I changed the folder name and added detailed workflow in README file. @prathimacode-hub .

**Comment by prathimacode-hub** [comment]
> > Changes to be done :
> > Rename the project name as Keypad Calculator" You can also include a detailed description for workflow and setup. @vaishnavighiradkar
> 
> @prathimacode-hub Ma'am should I change the PR and issue name too?

Let that be. I will do it up. @vaishnavighiradkar

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Impressive work. Awaiting to see what you come up with next. 👌✔@vaishnavighiradkar

**Pull request merged**
