### PR TITLE
feat: project button fixed

### PR DESCRIPTION
**Pull request by YalfamIamShaon**
issue no - #122 
Project button working fixed

### CODE REVIEW

**Comment by YalfamIamShaon** [comment]
Hi @prathimacode-hub. Could you please double-check the Project button's functionality?

**Comment by prathimacode-hub** [comment]
Include PR template and add the details of what you had done along with issue number. @YalfamIamShaon

**Comment by YalfamIamShaon** [comment]
okay, I'll do it..

**Comment by prathimacode-hub** [comment]
> okay, I'll do it..

What you will do? Hope you got my point. @YalfamIamShaon

**Pull request closed without merging**
