### PR TITLE
IoT-Spot : Heart Beat Monitor using Arduino #29

### PR DESCRIPTION
**Pull request by vaishnavighiradkar**
## Related Issue 

- Info about the related issue 

- [X] GSSOC Participant  
- [X] Contributor

Closes: #29 

### Describe the changes you've made

Added a Heart Beat Monitor System Using Arduino

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Simulated on proteus. When voltage on the potentiometer was changed attached to test pin of HeartBeat Sensor, BPM was printed accordingly on the virtual terminal.
## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Comment by vaishnavighiradkar** [comment]
Ma'am, I'm unable to add PR template. Please help me out.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Can you add zoomed in image of the circuit diagram. Connections aren't visible clearly.
Add appropriate comments in code to get good understanding of it.

@vaishnavighiradkar

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub  Changes done. please review.

**Review by Dhruvsinghjadon — COMMENTED** [review]
approved by me, let other mentors check and review it

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good choice of the project. Well done. 👏✔@vaishnavighiradkar

**Pull request merged**
