### PR TITLE
Display Time in LCD

### PR DESCRIPTION
**Pull request by CS50X-RGB**
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #169  that will be closed through this PR

### Describe the changes you've made
Added files for the project Display Time on LCD using Raspberry PI 

## Type of change

What sort of change have you made:
- [x] My code follows the code style of this project.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Use PR template, add issue number, details of your PR. Go through the contributing guidelines, naming format is not right. Elaborate your README file. Issue title and PR title should be same. @CS50X-RGB

**Comment by CS50X-RGB** [comment]
> Use PR template, add issue number, details of your PR. Go through the contributing guidelines, naming format is not right. Elaborate your README file. Issue title and PR title should be same. @CS50X-RGB 

Okk

**Review by CS50X-RGB — COMMENTED** [review]
Changed README file title

**Comment by CS50X-RGB** [comment]
@prathimacode-hub Now review plz

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Keep your folder name as "Display Time in LCD" and README needs to be more elaborate. You can refer to README template. @CS50X-RGB

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👌👏@CS50X-RGB

**Pull request merged**
