### PR TITLE
IoT-Spot : Home alert security system using Arduino #33

### PR DESCRIPTION
**Pull request by ritikalohia**
## Related Issue 

- Info about the related issue 

- [ ] DWOC Participant  
- [x] SWOC Participant 
- [ ] Contributor

Closes: #33 

### Describe the changes you've made

I have made a new folder named home alert security system, In which images, video , code and readme file are present. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been simulated on Tinkedcad, video is also in Images folder.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Image and video are uploaded in Images folder.
 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
Changes to be done : 

According to the guidelines mentioned, you project repo should be titled as "Home Security Alert System"
The project file can be renamed as "home_security_alert_system.ino"
Rename your readme file into README.md
Add appropriate comments in your code to get good understand of the project

Kindly do these changes. @ritikalohia

**Comment by ritikalohia** [comment]
@prathimacode-hub , i have modified the repo as said.

**Comment by prathimacode-hub** [comment]
I don't think all of the changes had done yet because I could still see few of it hasn't pushed. Can you check it once? @ritikalohia

**Comment by ritikalohia** [comment]
I think, nothing has left to done

**Comment by geetaroraqaz** [comment]
Correct a few grammatical mistakes
Try writing in MS Word first.

**Comment by geetaroraqaz** [comment]
[Minor Scripts/Arduino/Home Security Alert System/README.md](https://github.com/prathimacode-hub/IoT-Spot/pull/51/commits/27593d2e8a64bef6b1788139de01cc8553961ff9#diff-6e47336382384ad92201fd0dcfaee6fe767acb5da604a19ef111d79f85059765)

this one

**Comment by ritikalohia** [comment]
check the pr , please

**Comment by geetaroraqaz** [comment]
Still mistakes are present.
Try using MS Word it will point out mistakes.
Like u have written rotote instead of rotate and few others.

**Review by prathimacode-hub — APPROVED** [review]
Good choice of the script. Well justified. Keep raising. Impressive work. 👌🙌@ritikalohia

**Comment by ritikalohia** [comment]
thanks😁

**Pull request merged**
