### PR TITLE
Door Lock System using 8051 Microcontroller

### PR DESCRIPTION
**Pull request by nitishkumar07**
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #175 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
It has been tested by simulating it in Proteus
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
doorlock1
doorlock3
doorlock2

https://user-images.githubusercontent.com/70712427/162345300-c4a448db-fcf5-4378-b704-deadc03f507e.mp4

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Since this is a use case, add this project into "/Minor Scripts/8051" repository 
Also add few more appropriate comments in code to get good understanding of it. @nitishkumar07

**Comment by nitishkumar07** [comment]
I have done the changes
please check @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add the links of simulation file and schematics in README.md  @nitishkumar07

**Comment by nitishkumar07** [comment]
I have used Proteus so I have to add the folder which contain simulation files to the project and then put link to readme file?
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
> I have used Proteus so I have to add the folder which contain simulation files to the project and then put link to readme file? @prathimacode-hub

Yes, you already included them in "Images", just add the links in README file. @nitishkumar07

**Comment by nitishkumar07** [comment]
I have done changes please check
@prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Link adding should be of including the link present in this repository not from your repo. @nitishkumar07

**Comment by nitishkumar07** [comment]
I have changed the link
@prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Impressive work. Keep going. 👏🙌@nitishkumar07

**Pull request merged**
