### PR TITLE
Combination Lock using Arduino #188

### PR DESCRIPTION
**Pull request by SarthakSKumar**
### Related Issue:
Combination Lock using Arduino #188

- [x] GSSOC Participant
- [x] Contributor

Closes: #188 

### Type of Change:
Added a new folder under Arduino Scripts, which contains files for the "Combination Lock using Arduino" Project.
-New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
I have written and tested the code (.ino file) for Arduino. Compiles Successfully.
Attached is the block diagram for the Schematic Representation
Added the simulation video for the project

### Checklist:
- [x] My code follows the guidelines of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs, could you shift this project into "/Minor Script/Arduino" @SarthakSKumar

**Comment by SarthakSKumar** [comment]
I have made the requested changes ma'am. Sorry for the redundant commits @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Impressive work. You're showing great progress. Keep it up. 👌👏@SarthakSKumar

**Comment by prathimacode-hub** [comment]
> I have made the requested changes ma'am. Sorry for the redundant commits @prathimacode-hub

That's how we learn it. Every mistake is a way to get better. @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> > I have made the requested changes ma'am. Sorry for the redundant commits @prathimacode-hub
> 
> That's how we learn it. Every mistake is a way to get better. @SarthakSKumar

Thanks for the motivation ma'am. 🙏🙏

**Pull request merged**
