### PR TITLE
Adding a Folder of RC_CAR_CIRCUIT

### PR DESCRIPTION
**Pull request by rk18venom**
I am GSSOC Contributor.
I have added a folder of RC_car_circuit simulation.

### CODE REVIEW

**Review by geetaroraqaz — CHANGES_REQUESTED** [review]
in this change "will rotates" to "will rotate"
and change the 1st block diagram image to a clearer one or a zoomed in one

**Comment by prathimacode-hub** [comment]
@geetaroraqaz, @rk18venom is a GSSOC contributor. Still thanks for adding your suggestions to the contributor

@rk18venom, don't create PR without getting this issue assigned to you. If issue isn't created using [issue template](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/feature_request.md) to create, approach you would follow, tools you would use.

**Comment by rk18venom** [comment]
Can I close this pr and make a new one with proper changes as you all suggested to me?

**Comment by prathimacode-hub** [comment]
No need to close it. Do the changes mentioned in your forked repo and push it back, it will automatically replace the previous changes. @rk18venom

**Comment by rk18venom** [comment]
ok mam

**Comment by rk18venom** [comment]
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #55 

### Describe the changes you've made

Adding the new project on how to make RC circuit simulation on tinkercad.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

On Tinker Cad

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | [Screenshort](https://github.com/rk18venom/IoT-Spot/blob/RC_car_circuit/Arduino/RC%20car%20circuit/Images/RC_car_circuit_image.png) |
 Original Block Diagram | [Block Diagram](https://github.com/rk18venom/IoT-Spot/blob/RC_car_circuit/Arduino/RC%20car%20circuit/Images/Block_diagram.png) |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Work is good, but need changes in structuring. Once go through the README file of the project, structure has been provided.

**Comment by rk18venom** [comment]
Mam, I have just added the image file and the README file structure is also matching except for adding compilation steps because in this project I m not getting what I have to add in this section.

**Comment by rk18venom** [comment]
@prathimacode-hub @vilgad @geetaroraqaz ,mam please review it once, I have made all the changes that you have suggested to me. If any more changes are needed then tell me.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Rename your project folder as "RC Car Circuit" and project file as "RC_car_circuit.ino. Then it's ready to be merged. @rk18venom

**Comment by rk18venom** [comment]
Ok Mam, mam I have renamed the folder and file.

**Comment by prathimacode-hub** [comment]
Folder renaming still looks same here. Hope it's pushed correctly. @rk18venom

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Files you added in renamed folder consists of project file and README. But Images you added and video still shows up in old folder. @rk18venom

**Comment by rk18venom** [comment]
@prathimacode-hub I have done all the changes.

**Review by prathimacode-hub — APPROVED** [review]
Very well presented. Keep it up. PR approved. 🙌✨@rk18venom

**Comment by rk18venom** [comment]
Thank You, Mam. 😊

**Pull request merged**
