### PR TITLE
Portable Weight Limit Checker Using Arduino

### PR DESCRIPTION
**Pull request by shreya024**
## Related Issue 

- Portable Weight Limit Checker Using Arduino

- [x] GSSOC Participant  
- [ ] Contributor

Closes: #121  

### Describe the changes you've made

I have added code, readme, images and simulation video to implement a portable weight limit checker using Arduino

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Using tinkercad

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

portable_weight_limit_checker_using_arduino

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Add the project in "Minor Scripts/Arduino" folder
Rename the project folder to "Portable Weight Limit Checker"
Add "requirements.txt" file with things that went into the project
Simulation file instead of .gif convert it into .mp4 format.

Kindly do these changes @shreya024

**Comment by shreya024** [comment]
> Changes to be done :
> 
> Add the project in "Minor Scripts/Arduino" folder Rename the project folder to "Portable Weight Limit Checker" Add "requirements.txt" file with things that went into the project Simulation file instead of .gif convert it into .mp4 format.
> 
> Kindly do these changes @shreya024

@prathimacode-hub I have made the changes. Kindly check

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add simulation file link in README.md file @shreya024

**Review by prathimacode-hub — APPROVED** [review]
PR approved. You're doing a fab job. 🎉🤝@shreya024

**Comment by shreya024** [comment]
> PR approved. You're doing a fab job. 🎉🤝@shreya024

Thank you ma'am :)

**Pull request merged**
