### PR TITLE
Introduction to 8051 Microcontroller

### PR DESCRIPTION
**Pull request by SiddhantPawar03**
## Related Issue 

- Info about the related issue 

- [X] GSSOC Participant  
- [X] Contributor

Closes: #183

### Describe the changes you've made

Added new project - Introduction to 8051 Microcontroller

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
<br>
Made a word file, included information from various web sources as well as from material already I had. The motive was to deliver the best content regarding the 8051 Microcontroller.
<br>
Document Snippets:
image
image
image

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add short code snippets to showcase practically with things you had included in README @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
> Add short code snippets to showcase practically with things you had included in README @SiddhantPawar03

Updated! @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
At the end, give short summary of why 8051 is useful, where it is used and conclude it.
Then at the end of the file write your name @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
> At the end, give short summary of why 8051 is useful, where it is used and conclude it. Then at the end of the file write your name @SiddhantPawar03

Updated!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
PR approved. You had initiated the first documentation issue. Impressive. 👌👏
But a small change you didn't recognize it. This is a documentation on 8051 so it should be in this [link](https://github.com/prathimacode-hub/IoT-Spot/tree/main/8051/Documentation/Introduction%20to%208051). @SiddhantPawar03

**Pull request closed without merging**
