### PR TITLE
Basic RGB LED Blinking Using ESP8266/ Fix Issue#344

### PR DESCRIPTION
**Pull request by mukundsolanki**
## Related Issue 

- Basic RGB LED Blinking Using ESP8266

- [x] IWOC2.0 2024 Participant  
- [x] Contributor

Closes: #344 

### Describe the changes you've made

Added code and documentation for Basic RGB LED Blinking using ESP8266 while keeping the project structure in mind, I have added the code  under the `ESP8266` directory and also added some sample images for connecting the components...

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly look into project structure to know the miss outs. And also follow templates given for pull request and your Readme file of the project. @mukundsolanki

**Comment by mukundsolanki** [comment]
> ###

Updated the PR with template, and also added the proper readme file as given in the template + some images of basic diagrams

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Well done and keep contributing. Your first choice of project is good. 👌👍 @mukundsolanki

**Comment by prathimacode-hub** [comment]
Hola @mukundsolanki,

Hope you're doing well with your amazing open source contributions. On an appreciative note for adding your value to IoT-Spot in IWOC 2024, here is a same token of appreciation from my end.

You can connect with me through my socials here :

LinkedIn - https://www.linkedin.com/in/prathima-kadari/
Twitter - https://twitter.com/prathima_kadari

Mukund Solanki IWOC 2 0 Participation Certificate

**Pull request merged**
