### PR TITLE
Soil-Moisture-Detection-Using-Arduino

### PR DESCRIPTION
**Pull request by SiddhantPawar03**
## Related Issue 

- Info about the related issue 

- [X] GSSOC Participant  
- [X] Contributor

Closes: #31

### Describe the changes you've made

Added new project - Checking soil moisture level using temperature sensor databy using variety of conditions and printing in serial monitor in percentage format. Also added images and code for same.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
<br>
I have run this project on tinkercad simulation along with various parameters by placing manually.

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add the PR template provided to your PR message along with details of the issue and issue number for PR to be reviewed using edit option. @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub ig the PR template one, I have rename to template.md though any issue let me know. Few of the things I'm also not getting as I'm practicing contribution to open-source. Sorry to disturb you, hope you understand :)

**Comment by prathimacode-hub** [comment]
That's ok, Template should come in PR message and not in your PR. You can do so using edit option here. Add output screenshot in your README.md file and follow the project structure and file naming's given in the README file of the project. @SiddhantPawar03

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub ig the PR template one, I have rename to template.md though any issue let me know. Few of the things I'm also not getting as I'm practicing contribution to open-source. Sorry to disturb you, hope you understand :)

That's ok, it happens to every beginner. This means you're exploring it better and isn't a bad thing to ask queries. @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub added demonstration video as well as updated readme.md. Also updated template.
Do tell anything to do.
Also sorry for inconvenience though :)

**Comment by SiddhantPawar03** [comment]
## Related Issue 

- Info about the related issue 

- [X] GSSOC Participant  
- [X] Contributor

Closes: #15

### Describe the changes you've made

Added new project - Checking humidity level using neopixel and applying variety of conditions and printing in serial monitor the level of humidity. Also added images and code for same.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
<br>
I have run this project on tinkercad simulation along with various parameters by placing manually.

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by prathimacode-hub** [comment]
@sceary-expert, this is a PR not an issue. Express interest over issues by going to the respective tab.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
This particular PR has 2 projects? First thing when you do issues back to back before merging they get clubbed up into single PR. In that case you can create branch and send the PR. If you don't want confusion, you can do the PR's one after the other. 

Remove pull request templates from your added files. It should only show up as a PR message while creating PR. Follow the project structure provided in README file belong including the naming conventions. Is it 2 different issues or single? @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub I'm trying to delete PR template file but ig it's giving error shall I close this PR and again create PR for two different projects?

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub I'm trying to delete PR template file but ig it's giving error shall I close this PR and again create PR for two different projects?

You don't have to delete the PR. First thing you do is make your forked repo even with your main. Then you know where all you had added your files. So remove them directly from forked repo. Keep only soil moisture detection files and push it back again. It will change the PR here automatically. @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub updation done....
I'll create another new PR for Humdity sensing once this gets accepted!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

Keep your project folder as "Soil Moisture using Arduino"
Add the links of images and simulation video in README file
Workflow can be elaborated in README file. It's an application based file, so it needs some good detailing.
Add all the images and simulation file in "Images" folder. Simulation file should be in .mp4 format.
For images, include one zoomed in for screenshot as connections aren't visible. It should be legibly shown. You can add block diagram if possible too. 
Keep the filenames in snake case letters for project file : soil_moisture_detection.cpp
Add "requirements.txt" file, it should include all the requirements needed for this successful simulation of the project.

Kindly do these changes. @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
> Changes to be done 👍
> 
> Keep your project folder as "Soil Moisture using Arduino" Add the links of images and simulation video in README file Workflow can be elaborated in README file. It's an application based file, so it needs some good detailing. Add all the images and simulation file in "Images" folder. Simulation file should be in .mp4 format. For images, include one zoomed in for screenshot as connections aren't visible. It should be legibly shown. You can add block diagram if possible too. Keep the filenames in snake case letters for project file : soil_moisture_detection.cpp Add "requirements.txt" file, it should include all the requirements needed for this successful simulation of the project.
> 
> Kindly do these changes. @SiddhantPawar03

OK

**Pull request closed without merging**
