### PR TITLE
Obstacle avoidance

### PR DESCRIPTION
**Pull request by rk18venom**
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #143

### Describe the changes you've made

I have added the obstacle Avoidance Bot Circuit simulation folder in Arduino folder.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | [Image](https://github.com/rk18venom/IoT-Spot/blob/Obstacle-Avoidance/Arduino/Obstacle%20Avoidance%20Bot%20Circuit/Images/circuit_image.png) |
 Original Block Diagram | [Block Diagram](https://github.com/rk18venom/IoT-Spot/blob/Obstacle-Avoidance/Arduino/Obstacle%20Avoidance%20Bot%20Circuit/Images/block_diagram.png) |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add requirements.txt file @rk18venom

**Comment by rk18venom** [comment]
@prathimacode-hub mam changes have been made.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly add the project into "/Minor Scripts/Arduino" folder @rk18venom

**Comment by rk18venom** [comment]
@prathimacode-hub mam done

**Review by prathimacode-hub — APPROVED** [review]
PR approved.  Well executed project. Keep soaring. 👌✨@rk18venom

**Pull request merged**
