### PR TITLE
Automatic Room Temperature Controller

### PR DESCRIPTION
**Pull request by rk18venom**
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #155

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | [Screenshot](https://github.com/rk18venom/IoT-Spot/blob/Other/Minor%20Scripts/Arduino/Automatic%20Room%20Temperature%20Controller/Images/circuit_diagram.png) |
 Original Block Diagram | [Block Diagram](https://github.com/rk18venom/IoT-Spot/blob/Other/Minor%20Scripts/Arduino/Automatic%20Room%20Temperature%20Controller/Images/block_diagram.png) |

### CODE REVIEW

**Comment by rk18venom** [comment]
@prathimacode-hub mam, please review it.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Could you add comments to get good understanding of the code. @rk18venom

**Comment by rk18venom** [comment]
@prathimacode-hub mam, review it once again, please.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great choice. 🙌@rk18venom

**Pull request merged**
