### PR TITLE
VEHICLE ACCIDENT PREVENTION SYSTEM(ISSUE:#62)

### PR DESCRIPTION
**Pull request by rittikadeb**
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #62  

### Describe the changes you've made

Added a new project- Arduino Based Vehicle Accident Prevention System

## Type of change

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- I have run the code on the Arduino IDE which was successfully compiled without any errors.
- I have simulated the circuit with code in Tinkercad.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

image

[Tinkercad Simulation Video](https://github.com/rittikadeb/IoT-Spot-1/blob/main/Minor%20Scripts/Arduino/Vehicle%20Accident%20Prevention%20System/Images/vehicle_accident_prevention_system.mp4)

### CODE REVIEW

**Comment by abhisheks008** [comment]
Your project looks good to me and your presentation is also picture perfect. But one thing you can add into your cpp code by adding the comments around the functions. It makes the users to understand where and which function is working on which part of the project. Hope you understand what I am trying to say. Otherwise everything is ok! @rittikadeb

**Comment by rittikadeb** [comment]
Sure I will comment on the code

**Comment by rittikadeb** [comment]
Hey I have added the comments in the code file. Please review it.

**Comment by abhisheks008** [comment]
LGTM! Your PR is approved from my side @rittikadeb

**Review by prathimacode-hub — APPROVED** [review]
Picture Perfect PR. Your work is appreciated. Well done. Congrats. ✨🎉@rittikadeb

**Pull request merged**
