### PR TITLE
Calculator using 8051

### PR DESCRIPTION
**Pull request by nitishkumar07**
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #118 

### Describe the changes you've made

Give a clear description what modifications you have made
added new project 
calculator using 8051
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
sc3
sc1

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Screenshot is not visible in your PR template @nitishkumar07

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Rename the project title as "Simple Calculator" and add the project into "Minor Scripts/8051" folder
Include "requiremens.txt" file with all the things that have been needed for this project.

@nitishkumar07

**Comment by nitishkumar07** [comment]
I have have done the required changes
@prathimacode-hub  please check

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great going. 🙌✨ @nitishkumar07

**Pull request merged**
