### PR TITLE
Controlling LED Using IR Remote #160

### PR DESCRIPTION
**Pull request by vaishnavighiradkar**
## Related Issue 

- Info about the related issue 

- [X] GSSOC Participant  
- [X] Contributor

Closes: #160 

### Describe the changes you've made

Added a system to control blinking of LED light using IR Remote and IR sensor
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

When simulated and pressed power button of IR remote LED changed it's state from ON/OFF to OFF/ON

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

Circuit Diagram

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
This project should go under "/Arduino" folder and not minor scripts as it doesn't perform any use-case.

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub  Ma'am changes done. Please review.

**Review by Dhruvsinghjadon — COMMENTED** [review]
Approved by me

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub  Ma'am please review my pull request. I made the changes needed.

**Comment by Dhruvsinghjadon** [comment]
> @prathimacode-hub Ma'am please review my pull request. I made the changes needed.

Good

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Keep going. 👏🙌@vaishnavighiradkar

**Pull request merged**
