### PR TITLE
DC Motor Interfacing using 8051 Microcontroller

### PR DESCRIPTION
**Pull request by nitishkumar07**
## Related Issue 

- Info about the related issue 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #91 

### Describe the changes you've made

I have added  DC Motor Interfacing project 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
I have verified the code by running in simulator

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

dc motor

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Review by Dhruvsinghjadon — COMMENTED** [review]
Approved by me, Let other mentors check this one

**Comment by prathimacode-hub** [comment]
@nitishkumar07, can you reach out to me once.

**Review by Dhruvsinghjadon — COMMENTED** [review]
Approved by me

**Review by prathimacode-hub — APPROVED** [review]
Changes to be done :

Rename your project  folder as "DC Motor Interfacing"
Add appropriate comments in code file to get good understanding of the project
Include simulation file in the README.md

@nitishkumar07

**Comment by nitishkumar07** [comment]
I have done all the changes
@prathimacode-hub  please review it

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good spirit. Keep progressing. ✨👌@nitishkumar07

**Pull request merged**
