### PR TITLE
Update CODE_OF_CONDUCT.md and README.md (Under Arduino Scripts)

### PR DESCRIPTION
**Pull request by SarthakSKumar**
Added gramatical changes and removed inconsistencies in CODE_OF_CONDUCT.md
Made some changes in README.md under Arduino Scripts.
Please do review🙏

### CODE REVIEW

**Comment by SarthakSKumar** [comment]
Please do review @prathimacode-hub ma'am

**Comment by prathimacode-hub** [comment]
@SarthakSKumar, can you message me in discord.

**Comment by SarthakSKumar** [comment]
> @SarthakSKumar, can you message me in discord.

Sure ma'am

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good Initiation. ✨✔@SarthakSKumar

**Comment by SarthakSKumar** [comment]
> PR approved. Good Initiation. ✨✔@SarthakSKumar

Thank you ma'am

**Pull request merged**
