### PR TITLE
Basic led blinking using arduino

### PR DESCRIPTION
**Pull request by SarthakSKumar**
### Related Issue:
IoT-Spot: Basic LED Blinking using Arduino #4 

- [x] GSSOC Participant
- [x] Contributor

Closes: #4 

### Type of Change:
Added a new folder under Arduino Scripts, which contains files for the "Basic LED Blinking using Arduino" Project.
-New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
I have written and tested the code (.ino file) for Arduino. Compiles Successfully.
Attached the block diagram for the Schematic Representation
Added Simulation Video

### Checklist:
- [x] My code follows the guidelines of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
@SarthakSKumar your PR looks good to me, approved from my side.

**Comment by SarthakSKumar** [comment]
> @SarthakSKumar your PR looks good to me, approved from my side.

Thank you for the reply.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs, keep your project file name in snake case : Basic_LED_Binking_using_Arduino.ino @SarthakSKumar

**Comment by SarthakSKumar** [comment]
I have pushed the renamed file to the branch. Do I create another pull request or can I do something with the same one ma'am?

**Review by Dhruvsinghjadon — COMMENTED** [review]
Approved from my side

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great going. 🙌👌@SarthakSKumar

**Pull request merged**
