### PR TITLE
Speeding motor using arduino

### PR DESCRIPTION
**Pull request by baibhav3211**
I have added images, videos and the code for the project "Speeding motor using arduino".
Do review and merge the pr.
Thanks :)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly add PR template, add up the details and issue number. Issue title and PR title should be same. For README.md file, we have a template as well to follow

[PR Template](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/pullrequest_template.md)
[README.md](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/readme_template.md)  

Add appropriate comments in code to get good understanding of the project @baibhav3211

**Comment by baibhav3211** [comment]
## Related Issue 

- Info about the related issue 

- [ ] DWOC Participant  
- [ x] SWOC Participant 
- [ ] Contributor

Closes: #11

### Describe the changes you've made

Added a program to control the speed of a DC motor using arduino.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The project is verified on tinkercad platform and the video of the simulation is also added.

## Checklist:

- [x ] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

Uploaded in the images folder.

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

**Comment by prathimacode-hub** [comment]
Add appropriate comments in code to get good understanding of the project @baibhav3211

**Review by geetaroraqaz — COMMENTED** [review]
Add comments

**Comment by baibhav3211** [comment]
Done!

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good work. Keep progressing. Congrats on your first PR. Welcome to repo officially. 👏🎉

**Pull request merged**
