### PR TITLE
Added CSS hover effects

### PR DESCRIPTION
**Pull request by MonalikaPatnaik**
Improved the inclusion part in the website by adding CSS hover effects by introducing respective changes .
This fixes #226
Kindly merge my pull request.
Thank you so much for assigning this issue to me.
image

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
This is not how I expected it. We need something more to this. Could you? I think we should have a call on this. @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
> This is not how I expected it. We need something more to this. Could you? I think we should have a call on this. @MonalikaPatnaik

Apologies for any inconvenience if happened. I would be grateful if you tell me how could I improve.

**Comment by prathimacode-hub** [comment]
No worries, we will have a meet tomorrow. Tell me ur possible time for a conversation. You can drop me a message on Discord and I will share you the meet link with you. @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
> No worries, we will have a meet tomorrow. Tell me ur possible time for a conversation. You can drop me a message on Discord and I will share you the meet link with you. @MonalikaPatnaik

Yeah sure...After 6 pm we can have a conversation.
Thankyou!!

**Comment by MonalikaPatnaik** [comment]
Hello @prathimacode-hub , kindly review my code and let me know of any issues if there.
Thankyou!!

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Well done. 👌👍@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
> PR approved. Well done. 👌👍@MonalikaPatnaik

Thank you so much ma'am for merging my pull request..it gives me immense pleasure and a new boost of confidence to contribute in more and more such projects..
Thanks !!

**Pull request merged**
