### PR TITLE
Color Detection on LCD using Arduino 

### PR DESCRIPTION
**Pull request by CS50X-RGB**
Related Issue 

- Color Detection on LCD using Arduino

- [x] GSSOC Participant  
- [x] Contributor

Closes: issue #25 
### Describe the changes you've made
Added a files regarding printing color on the LCD using a color sensor
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add circuit and block diagram in readable format and include the simulation file. @CS50X-RGB

**Review by CS50X-RGB — COMMENTED** [review]
Added files @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Include circuit, block diagram and demo into "Images" folder. @CS50X-RGB

**Comment by CS50X-RGB** [comment]
@prathimacode-hub  Made the changes mam as per said plz review it

**Review by prathimacode-hub — APPROVED** [review]
Images and demo aren't added up in "Images" folder but it is inside "Circuit-Setup" folder. I said the same change earlier too. I guess you haven't gone through the project structure. But anyways,  I'm accepting it now. Next time, follow this as part of project structure for upcoming PR's

@CS50X-RGB

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Keep progressing. Good spirit. Well done. 👌✔@CS50X-RGB

**Comment by CS50X-RGB** [comment]
Thanks maam sry for not following file structure I will keep it mind for next time

**Pull request merged**
