### PR TITLE
Fixed social icons alignment in contact us section

### PR DESCRIPTION
**Pull request by Anirban-1490**
## Related Issue 

social icons alignment problem in  contact us section

- [x] GSSOC Participant  
- [x] Contributor

Closes: #63 

### Describe the changes you've made

changed alignment of the icons

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

tested in my browser

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original 

Opera Snapshot_2022-03-02_154520_prathimacode-hub github io

Current 

Opera Snapshot_2022-03-02_154420_prathimacode-hub github io

### CODE REVIEW

**Comment by abhisheks008** [comment]
LGTM! Your PR is approved from my side.

**Comment by Anirban-1490** [comment]
> LGTM! Your PR is approved from my side.

**Comment by abhisheks008** [comment]
@Anirban-1490 don't close it. Whenever your PR is merged you'll get notified.

**Comment by Anirban-1490** [comment]
> @Anirban-1490 don't close it. Whenever your PR is merged you'll get notified.

yeah ik . i clicked by mistake 😅

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Welcome to repo. Kudos to your observations. 👏@Anirban-1490

**Comment by Anirban-1490** [comment]
> PR approved. Welcome to repo. Kudos to your observations. 👏@Anirban-1490

nice, thanks

**Pull request merged**
