### PR TITLE
Improved the CSS part of navigation tabs, contact page and buttons.

### PR DESCRIPTION
**Pull request by vedsom**
## Related Issue 

Currently when we hover over the option it has black background.
And in contact page it has gray background with black color input which decreses the visisbility.
About and contact us button also doesn't have great effect which tells that button is clicked or not 

- [x] GSSOC Participant  
- [x] Contributor

Closes: #253

### Describe the changes you've made

1.Improve the CSS part of navigation tabs by matching website theme, which makes it more attractive.
2.Add animation, pressed affect over about and contact us button which makes it more clear when button got pressed.
3.By changing te colors of contact us background and making send mail button more attractive.
4.Make Inclusion part little hoverable

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

My observing the functioning of code before and after the changes

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

https://user-images.githubusercontent.com/96954912/171105068-2a44ae28-8288-4590-a0f6-69c23261537a.mp4

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

### CODE REVIEW

**Comment by vedsom** [comment]
@prathimacode-hub mam, here's the work done, please review the PR. If possible please mark it Level 2. I have added animation and pressed affect over buttons which gives it great view. Rest your choice and thankyou so much for assigning the task.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Sorry to say, but it's a level 1 issue. @vedsom

**Comment by vedsom** [comment]
> PR approved. Sorry to say, but it's a level 1 issue. @vedsom

No worries mam. Thanku so much for supporting whole session, you are a great admin mam

**Comment by prathimacode-hub** [comment]
Most welcome. Loved your presence as a collaborator. 😀@vedsom

**Pull request merged**
