### PR TITLE
Fixed Contact is button - Issue #266

### PR DESCRIPTION
**Pull request by prjailani**
Hi sir,
   I fixed this issue. Now, the contact us button works fine. If there's something else I am missing there, let me know. Thanks.

### CODE REVIEW

**Review by Harshil-Jani — CHANGES_REQUESTED** [review]
Don't delete the IoT-Spot Submodule.

**Comment by Harshil-Jani** [comment]
Hey @prjailani Since you are already working for the footer part, Can you help making the UI for the Contact Form bit more classy with animations?
image

Also, just fix your last commit where you had deleted the submodule of IoT-Spot.

**Comment by Harshil-Jani** [comment]
Closing Due to Inactivity

**Comment by prjailani** [comment]
Hi sir, I has some other works that's why I am unable to do this. So, can you please reopen this.

**Comment by prjailani** [comment]
> Hi sir, I has some other works that's why I am unable to do this. So, can you please reopen this.

@Harshil-Jani

**Comment by Harshil-Jani** [comment]
@prjailani  I saw that, You have deleted the fork . So, I cannot help you out. Since your fork is deleted we cannot reopen your PR. All your changes have lost from your side as well.

**Pull request closed without merging**
